package com.bjpowernode.crm.settings.dictionary.value.mapper;

import com.bjpowernode.crm.settings.dictionary.value.pojo.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Thu Jul 13 10:35:43 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Thu Jul 13 10:35:43 CST 2023
     */
    int insert(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Thu Jul 13 10:35:43 CST 2023
     */
    int insertSelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Thu Jul 13 10:35:43 CST 2023
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Thu Jul 13 10:35:43 CST 2023
     */
    int updateByPrimaryKeySelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Thu Jul 13 10:35:43 CST 2023
     */
    int updateByPrimaryKey(DicValue row);

    /**
     * 根据typeCode查询数据字典表
     * @param typeCode
     * @return
     */
    List<DicValue> selectDicValueByDicTypeCode(String typeCode);

    /**
     * 根据id查询DicValue
     * @param id
     * @return
     */
    String selectDicValueByDicTyId(String id);
}